[package]
name = "rividb"
version = "0.1.0"
authors = ["Ahmed Mostafa <amk67482@gmail.com>"]
license = "MIT"
discription = "Fast in-memory analytics datastore in Rust"

[dependencies]
serde_json = "1.0"
time = "0.1"
nom = "^4.2"
heapsize = "^0.4"
